repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
        - id: terraform_fmt
        - id: terraform_validate
        # - id: terraform_tflint
        - id: terraform_docs
          args:
              - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
              - --hook-config=--add-to-existing-file=false     # Boolean. true or false
              - --hook-config=--create-file-if-not-exist=true # Boolean. true or false

  # Pre-commit gen√©ricos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
