name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: read # Permissão para ler o repositório
  id-token: write # Conexão com o provedor de identidade

env:
    GCP_REGION: southamerica-east1

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: GCP Autentication
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GCP_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Tag Docker image and push to Google Artifact Registry
        id: docker-push-tagged
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
              ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY }}/gcp_image_process:latest

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          service: ${{ env.GCP_SERVICE_NAME }}
          image: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY }}/gcp_image_process:latest
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: ${{ env.GCP_REGION }}
